TechBlog/Models/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations.Schema;
using TechBlog.Models;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace TechBlog.Models
{
    public class Post
    {
        public Post()
        {
            this.Date = DateTime.Now;
        }

        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(200)]
        public string Title { get; set; }

        [AllowHtml]
        [Required]
        [DataType(DataType.MultilineText)]
        public string Body { get; set; }


        [Required]
        public DateTime Date { get; set; }

        public string Author_Id { get; set; }

        [ForeignKey("Author_Id")]
        public ApplicationUser Author { get; set; }

        public Comment Comment { get; set; }

        public ICollection<Comment> Comments { get; set; }
        public ICollection<Replay> Replays { get; set; }

        public int CommentsCount { get; set; }
    }
}

TechBlog/Controllers/CommentsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechBlog.Extensions;
using TechBlog.Models;

namespace TechBlog.Controllers
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        public ActionResult Index()
        {
            return View(db.Comments.Include(p => p.Author).OrderByDescending(b => b.Date).ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Include(b => b.Author).Single(b => b.Id == id);
            var replays = db.Replays.Where(p => p.Comment_Id == comment.Id).Include(b => b.Author).ToList();
            comment.Replays = replays;

            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        [HttpGet]
        public ActionResult Create(Comment Comment, int? id)
        {
            var post = db.Posts.Find(id).Id;
            Comment.Post_Id = post;
            return View(Comment);
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Body,Author_Id,Post_Id")] Comment Comment, int id)
        {
            if (ModelState.IsValid)
            {
                UserManager<ApplicationUser> UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                ApplicationUser user = UserManager.FindById(this.User.Identity.GetUserId());
                Comment.Author = user;

                var postId = db.Posts.Find(id).Id;
                Comment.Post_Id = postId;
                Post post = db.Posts.Find(id);
                Comment.Post = post;
                post.CommentsCount = post.CommentsCount + 1;

                db.Comments.Add(Comment);
                db.SaveChanges();
                return RedirectToAction("Details", "Posts", new { id = post.Id });
            }

            return View();
        }

        // GET: Comments/Edit/5
        [HttpGet]
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            Comment postAuthor = db.Comments.Include(b => b.Author).Single(b => b.Id == id);

            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,Body,Date,Post_Id,Author_Id")] Comment comment, int id)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;

                UserManager<ApplicationUser> UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                ApplicationUser user = UserManager.FindById(this.User.Identity.GetUserId());
                comment.Author = user;

                var postId = db.Posts.Find(id).Id;
                comment.Post_Id = postId;
                Post post = db.Posts.Find(id);  
                comment.Post = post;

                db.SaveChanges();
                this.AddNotification("Comment Edited.", NotificationType.INFO);

                return RedirectToAction("Details", "Posts", new { id = post.Id });
            }
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            Post post = db.Posts.Find(comment.Post_Id);
            db.Comments.Remove(comment);
            post.CommentsCount = post.CommentsCount - 1;
            db.SaveChanges();
            return RedirectToAction("Index", "Posts", null);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechBlog/Controllers/PostsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechBlog.Extensions;
using TechBlog.Models;

namespace TechBlog.Controllers
{
    public class PostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Posts
        public ActionResult Index()
        {
            return View(db.Posts.Include(p => p.Author).OrderByDescending(b => b.Date).ToList());
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Include(b => b.Author).Single(b => b.Id == id);

            var comments = db.Comments.Where(p => p.Post_Id == post.Id).Include(b => b.Author).ToList();
            var replays = db.Replays.Where(p => p.ReplayPost_Id == post.Id).Include(b => b.Author).ToList();

            post.Comments = comments;
            post.Replays = replays;

            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: Posts/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Body,PostLike,Author_Id")] Post post)
        {
            if (ModelState.IsValid)
            {
                UserManager<ApplicationUser> UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                ApplicationUser user = UserManager.FindById(this.User.Identity.GetUserId());
                post.Author = user;

                db.Posts.Add(post);
                db.SaveChanges();
                this.AddNotification("Post Created.", NotificationType.INFO);
                return RedirectToAction("Index");
            }

            return View(post);
        }


        // GET: Posts/Edit/5
        [HttpGet]
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }

            Post postAuthor = db.Posts.Include(b => b.Author).Single(b => b.Id == id);

            return View(post);

        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,Title,Body,Data,Author_Id")] Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;

                UserManager<ApplicationUser> UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                ApplicationUser user = UserManager.FindById(this.User.Identity.GetUserId());
                post.Author = user;
                db.SaveChanges();
                this.AddNotification("Post Edited.", NotificationType.INFO);

                return RedirectToAction("Index");
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            this.AddNotification("Post Deleted.", NotificationType.INFO);

            return RedirectToAction("Index");
        }

        // GET: MyPosts
        public ActionResult MyPosts()
        {
            return View(db.Posts.Include(p => p.Author).OrderByDescending(b => b.Date).ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechBlog/Controllers/ReplaysController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechBlog.Extensions;
using TechBlog.Models;

namespace TechBlog.Controllers
{
    public class ReplaysController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Replays
        public ActionResult Index()
        {
            var replays = db.Replays.Include(r => r.Author).Include(r => r.Comment);
            return View(replays.ToList());
        }

        // GET: Replays/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Replay replay = db.Replays.Find(id);
            if (replay == null)
            {
                return HttpNotFound();
            }
            return View(replay);
        }

        // GET: Replays/Create
        public ActionResult Create(Replay Replay, int? id)
        {
            var comment = db.Comments.Find(id).Id;
            Replay.Comment_Id = comment;

            var post = db.Comments.Find(id).Post_Id;
            Replay.ReplayPost_Id = post;
            return View(Replay);
        }

        // POST: Replays/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Body,Date,Author_Id,Comment_Id")] Replay replay, int id)
        {
            if (ModelState.IsValid)
            {
                UserManager<ApplicationUser> UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                ApplicationUser user = UserManager.FindById(this.User.Identity.GetUserId());
                replay.Author = user;

                var commentId = db.Comments.Find(id).Id;
                replay.Comment_Id = commentId;
                Comment comment = db.Comments.Find(id);
                replay.Comment = comment;

                var postId = db.Comments.Find(id).Post_Id;
                replay.ReplayPost_Id = postId;

                db.Replays.Add(replay);
                db.SaveChanges();
                return RedirectToAction("Details", "Posts", new { id = postId });
            }
            return View(replay);
        }

        // GET: Replays/Edit/5
        public ActionResult Edit(Replay Replay,int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Replay replay = db.Replays.Find(id);
            if (replay == null)
            {
                return HttpNotFound();
            }

            Replay postAuthor = db.Replays.Include(b => b.Author).Single(b => b.Id == id);
            //var comment = db.Comments.Find(id).Id;
            //Replay.Comment_Id = comment;

            //var post = db.Comments.Find(id).Post_Id;
            //Replay.ReplayPost_Id = post;

            return View(replay);
        }

        // POST: Replays/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Body,Date,Author_Id,Post_Id,Comment_Id")] Replay replay, int id)
        {
            if (ModelState.IsValid)
            {
                db.Entry(replay).State = EntityState.Modified;

                UserManager<ApplicationUser> UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                ApplicationUser user = UserManager.FindById(this.User.Identity.GetUserId());
                replay.Author = user;

                var commentId = db.Comments.Find(id).Id;
                replay.Comment_Id = commentId;
                Comment comment = db.Comments.Find(id);
                replay.Comment = comment;

                var postId = db.Comments.Find(id).Post_Id;
                replay.ReplayPost_Id = postId;

                db.SaveChanges();
                this.AddNotification("Replay Edited.", NotificationType.INFO);

                return RedirectToAction("Details", "Posts", new { id = postId});
            }

            return View(replay);
        }

        // GET: Replays/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Replay replay = db.Replays.Find(id);
            if (replay == null)
            {
                return HttpNotFound();
            }
            return View(replay);
        }

        // POST: Replays/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Replay replay = db.Replays.Find(id);
            db.Replays.Remove(replay);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TechBlog/Views/Posts/Create.cshtml
@model TechBlog.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create new post</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="btn btn-default">
    
        @Html.ActionLink("Back to List", "Index")
    
</div>

<script>
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('Body');
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TechBlog/Views/Posts/Delete.cshtml
@model TechBlog.Models.Post

@{
    ViewBag.Title = "Delete";
}


<h3>Are you sure you want to delete @Html.Raw(Model.Title)?</h3>
<div>       
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            <div class="btn btn-default">@Html.ActionLink("Cancel", "Index")</div>
        </div>
    }
</div>

TechBlog/Views/Posts/Details.cshtml
@model TechBlog.Models.Post

@{
    ViewBag.Title = "Details";
}


<div>
    <article class="details-blog-teaser">
        <header>
            <h2 class="details-title">@Html.DisplayFor(model => model.Title)</h2>
            <div class="about">
                Posted on <i>@Html.DisplayFor(model => model.Date)</i>
                @if (@Html.DisplayFor(model => model.Author) != null)
                {
                    @:by <i>@Html.DisplayFor(model => model.Author.FullName) (@Html.DisplayFor(model => model.Author.UserName))</i>
                }
            </div>
            <hr>
        </header>
        <div class="details-body">@Html.Raw(Model.Body)</div>
        <div class="clearfix text-center">

            <div class="details-body">
                @foreach (var comment in Model.Comments)
                {
                    if (comment != null)
                    {
                        <div class="details-blog-teaser text-center">
                            <div class="about text-center">
                                Posted on <i>@Html.DisplayFor(c => comment.Date)</i>
                                @if (@Html.DisplayFor(c => comment.Author) != null)
                                {
                                    @:by <i>@Html.DisplayFor(c => comment.Author.FullName) (@Html.DisplayFor(c => comment.Author.UserName))</i>
                                }
                            </div>
                            <hr>
                            @Html.Raw(comment.Body)
                            <hr>
                            @if (User.IsInRole("Administrators") || (comment.Author != null && User.Identity.Name == comment.Author.UserName))
                            {
                                <div class="btn btn-default">
                                    @Html.ActionLink("Delete", "Delete", "Comments", new { id = comment.Id }, null)
                                </div>
                            }

                            @*@* Replay code -------------------------------------- *@

                            @*<div class="details-body">
                                @foreach (var replay in Model.Replays)
                                {
                                    if (replay != null)
                                    {
                                        <div class="details-blog-teaser text-center">
                                            <div class="about text-center">
                                                Posted on <i>@Html.DisplayFor(c => replay.Date)</i>
                                                @if (@Html.DisplayFor(c => replay.Author) != null)
                                                {
                                                    @:by <i>@Html.DisplayFor(c => replay.Author.FullName) (@Html.DisplayFor(c => replay.Author.UserName))</i>
                                }
                                            </div>
                                            <hr>
                                            @Html.Raw(replay.Body)
                                            <hr>
                                            @if (User.IsInRole("Administrators") || (replay.Author != null && User.Identity.Name == replay.Author.UserName))
                                            {
                                                <div class="btn btn-default">
                                                    @Html.ActionLink("Edit", "Edit", "Replays", new { id = replay.Id }, null)
                                                </div>
                                            }
                                            @if (User.IsInRole("Administrators") || (replay.Author != null && User.Identity.Name == replay.Author.UserName))
                                            {
                                                <div class="btn btn-default">
                                                    @Html.ActionLink("Delete", "Delete", "Replays", new { id = replay.Id }, null)
                                                </div>
                                            }
                                        </div>
                                    }
                                }
                            </div>*@
                            
                            @* Replay code----------------------END *@
                            @*<div class="btn btn-default">
                                @Html.ActionLink("Create a Replay", "Create", "Replays", new { id = comment.Id }, null)
                            </div>*@
                        </div>                         
                    }
                }
            </div>

            <div class="btn btn-default">
                @Html.ActionLink("Create a Comment", "Create", "Comments", new { id = Model.Id }, null)
            </div>
        </div>
    </article>
</div>

<p>
    @if (User.IsInRole("Administrators") || (Model.Author != null && User.Identity.Name == Model.Author.UserName))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) @:|
        @Html.ActionLink("Delete", "Delete", new { id = Model.Id })
    }
    <div class="btn btn-default">
        @Html.ActionLink("Back to Posts", "Index")
    </div>
</p>

TechBlog/Views/Posts/Edit.cshtml
@model TechBlog.Models.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit post</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script>
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('Body');
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TechBlog/Views/Posts/Index.cshtml
@model IEnumerable<TechBlog.Models.Post>

@helper Truncate(string input, int length)
{
if (input.Length <= length)
{
        @Html.Raw(input)
}
else
{
        @Html.Raw(input.Substring(0, length)) <text>...</text>
}
}

@{
    ViewBag.Title = "Posts";
}
<header class="all-posts"><h2>All Posts</h2></header>
<body class="background-index">
    <h4 class="create-new">@Html.ActionLink("Create New", "Create")</h4>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Body)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {

            <tr>
                <td>

                    @Truncate(item.Title, 50)

                </td>
                <td>

                    @Truncate(item.Body, 160)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</body>

TechBlog/Views/Posts/MyPosts.cshtml
@model IEnumerable<TechBlog.Models.Post>

@helper Truncate(string input, int length)
{
    if (input.Length <= length)
    {
        @Html.Raw(input)
    }
    else
    {
        @Html.Raw(input.Substring(0, length)) <text>...</text>
    }
}

@{
    ViewBag.Title = "My Posts";
}

<h2>My Posts</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        if ((User.IsInRole("Administrators") && User.Identity.Name == item.Author.UserName) || item.Author != null && User.Identity.Name == item.Author.UserName)
        {
            <tr>
                <td>

                    @Truncate(item.Title, 50)

                </td>
                <td>

                    @Truncate(item.Body, 160)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @*@if (User.IsInRole("Administrators") || (item.Author != null && User.Identity.Name == item.Author.UserName))
                        {*@
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    @*}*@

                    @Html.ActionLink("Details", "Details", new { id = item.Id })

                    @*@if (User.IsInRole("Administrators") || (item.Author != null && User.Identity.Name == item.Author.UserName))
                        {*@
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    @* } *@
                </td>
            </tr>
        }
    }

</table>